author: Toofifty
database: false
description: Connects the Rapid server to IRC
main: me.toofifty.plugins.rapidirc.RapidIRC
name: RapidIRC
startup: startup
url: http://rapidcraftmc.com/
version: 0.3

commands:
    irc:
        description: Basic RapidIRC commands
        usage: /irc [list]
        permission: rapidirc.irc
        permission-message: You don't have permission for that.
    imsg:
        description: RapidIRC private messaging
        usage: /imsg [nick] [message...]
        permission: rapidirc.imsg
        permission-message: You don't have permission for that.
    ircop:
        description: OP RapidIRC commands
        usage: /ircop [start|stop|restart]
        permission: rapidirc.ircop
        permission-message: You don't have permission for that.
        
permissions:
    rapidirc.*:
        description: Gives access to all commands
        children:
            rapidirc.irc: true
            rapidirc.imsg: true
            rapidirc.ircop: true
            rapidirc.chatcolors: true
    rapidirc.irc:
        description: Basic RapidIRC commands
        default: op
    rapidirc.imsg:
        description: RapidIRC private messaging
        default: op
    rapidirc.ircop:
        description: OP RapidIRC commands
        default: op
    rapidirc.chatcolors:
        description: Allows use of chat colors
        default: op